# Site settings
title: Ainsley Wagoner
email: ainsley.wagoner@gmail.com
description: > # Ainsley Wagoner Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ainsleywagoner.com" # the base hostname & protocol for your site
twitter_username: ainsleywagon
github_username:  ainsleywagon

# Build settings
markdown: kramdown
